const KEY='scoreAnalyzerV44';
let subjects=JSON.parse(localStorage.getItem(KEY)||'null')||[{name:'语文',full:150},{name:'数学',full:150},{name:'英语',full:150}];
let students=[];
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(subjects))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderSubjects(){
 $('subjects').innerHTML=subjects.map((s,i)=>`<div class="subject-row"><input class="subject-input sname" data-i="${i}" value="${esc(s.name)}" placeholder="科目名称"><input class="subject-input sfull" data-i="${i}" type="number" min="1" value="${s.full}" placeholder="满分"><button data-del="${i}">删除</button></div>`).join('');
 document.querySelectorAll('.sname').forEach(x=>x.oninput=()=>{subjects[x.dataset.i].name=x.value.trim();save();refresh();});
 document.querySelectorAll('.sfull').forEach(x=>x.oninput=()=>{subjects[x.dataset.i].full=Math.max(1,Number(x.value)||1);save();refresh();});
 document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{if(subjects.length<=1){alert('至少保留一个科目');return} subjects.splice(Number(x.dataset.del),1);save();renderSubjects();refresh();});
}
$('addSubject').onclick=()=>{subjects.push({name:'新科目',full:100});save();renderSubjects();refresh();setTimeout(()=>{const a=document.querySelectorAll('.sname');a[a.length-1]?.select()},0)};
function rank(arr,key){const vals=arr.map(x=>Number(x[key])).filter(Number.isFinite).sort((a,b)=>b-a);const unique=[...new Set(vals)];return v=>{if(!Number.isFinite(Number(v)))return '-';return unique.indexOf(Number(v))+1}}
function refresh(){if(!students.length)return;renderOverview();renderRank();renderSubjectStats();renderFocus();}
function renderOverview(){const totals=students.map(s=>s.total);$('overview').classList.remove('hidden');$('overview').innerHTML=`<h2>班级总览</h2><div class="cards"><div class="card">人数<b>${students.length}</b></div><div class="card">平均总分<b>${avg(totals).toFixed(1)}</b></div><div class="card">最高总分<b>${Math.max(...totals)}</b></div><div class="card">最低总分<b>${Math.min(...totals)}</b></div></div>`}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function renderRank(){const sel=$('sortBy');const old=sel.value;sel.innerHTML='<option value="total">按总分排名</option>'+subjects.map((s,i)=>`<option value="s${i}">${esc(s.name)}排名</option>`).join('');if([...sel.options].some(o=>o.value===old))sel.value=old;const key=sel.value==='total'?'total':`s${sel.value.slice(1)}`;const data=[...students].sort((a,b)=>Number(b[key]??-Infinity)-Number(a[key]??-Infinity));const r=rank(data,key);$('rankTable').innerHTML='<thead><tr><th>排名</th><th>姓名</th><th>总分</th>'+subjects.map(s=>`<th>${esc(s.name)}</th>`).join('')+'</tr></thead><tbody>'+data.map(s=>`<tr><td>${r(s[key])}</td><td>${esc(s.name)}</td><td>${s.total}</td>${subjects.map((_,i)=>`<td>${s[`s${i}`]??'-'}</td>`).join('')}</tr>`).join('')+'</tbody>';$('rankSection').classList.remove('hidden')}
$('sortBy').onchange=renderRank;
function renderSubjectStats(){const rows=subjects.map((s,i)=>{const vals=students.map(x=>Number(x[`s${i}`])).filter(Number.isFinite);return `<tr><td>${esc(s.name)}</td><td>${avg(vals).toFixed(1)}</td><td>${(avg(vals)/s.full*100).toFixed(1)}%</td><td>${vals.length?Math.max(...vals):'-'}</td><td>${vals.length?Math.min(...vals):'-'}</td></tr>`}).join('');$('subjectTable').innerHTML='<thead><tr><th>科目</th><th>平均分</th><th>平均得分率</th><th>最高分</th><th>最低分</th></tr></thead><tbody>'+rows+'</tbody>';$('subjectSection').classList.remove('hidden')}
function renderFocus(){const list=students.filter(s=>subjects.some((sub,i)=>{const v=Number(s[`s${i}`]);return Number.isFinite(v)&&v<sub.full*.6}));$('focusList').innerHTML=list.length?list.map(s=>{const bad=subjects.map((sub,i)=>({sub,i})).filter(({sub,i})=>Number(s[`s${i}`])<sub.full*.6).map(({sub,i})=>`${esc(sub.name)} ${s[`s${i}`]}/${sub.full}`);return `<div class="focus-item"><b>${esc(s.name)}</b>　总分 ${s.total}<div>${bad.map(x=>`<span class="tag">${x} 不及格</span>`).join('')}</div></div>`}).join(''):'<p class="muted">暂无需要重点关注的学生</p>';$('focusSection').classList.remove('hidden')}
function searchStudent(){const name=$('studentName').value.trim();const s=students.find(x=>x.name===name);if(!s){$('studentResult').innerHTML='<p class="muted">没有找到该学生，请检查姓名。</p>';return}const totalRank=rank(students.map(x=>({...x})).sort((a,b)=>b.total-a.total),'total')(s.total);const highest=subjects.map((sub,i)=>({name:sub.name,rate:Number(s[`s${i}`])/sub.full})).filter(x=>Number.isFinite(x.rate));const max=Math.max(...highest.map(x=>x.rate)),min=Math.min(...highest.map(x=>x.rate));const adv=highest.filter(x=>Math.abs(x.rate-max)<1e-10).map(x=>x.name).join('、');const weak=highest.filter(x=>Math.abs(x.rate-min)<1e-10).map(x=>x.name).join('、');$('studentResult').innerHTML=`<div class="student-box"><h3>${esc(s.name)}</h3><p>总分：<b>${s.total}</b>　班级排名：<b>${totalRank}/${students.length}</b></p><table><thead><tr><th>科目</th><th>成绩</th><th>满分</th><th>得分率</th><th>科目排名</th></tr></thead><tbody>${subjects.map((sub,i)=>{const key=`s${i}`;const arr=students.filter(x=>Number.isFinite(Number(x[key]))).sort((a,b)=>Number(b[key])-Number(a[key]));const rr=rank(arr,key);return `<tr><td>${esc(sub.name)}</td><td>${s[key]??'-'}</td><td>${sub.full}</td><td>${Number.isFinite(Number(s[key]))?(Number(s[key])/sub.full*100).toFixed(1)+'%':'-'}</td><td>${rr(s[key])}</td></tr>`}).join('')}</tbody></table><p>优势科目：<b>${esc(adv||'-')}</b><br>薄弱科目：<b>${esc(weak||'-')}</b></p></div>`}
$('searchBtn').onclick=searchStudent;$('studentName').onkeydown=e=>{if(e.key==='Enter')searchStudent()};
$('fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json(ws,{defval:''});if(!raw.length)throw Error('Excel没有数据');const headers=Object.keys(raw[0]);const nameHeader=headers.find(h=>String(h).trim()==='姓名')||headers.find(h=>String(h).trim().includes('姓名'))||headers[0];students=raw.map(row=>{const s={name:String(row[nameHeader]??'').trim()};let total=0;subjects.forEach((sub,i)=>{const h=headers.find(x=>String(x).trim()===sub.name);const v=h===undefined?'':Number(String(row[h]).trim());s[`s${i}`]=Number.isFinite(v)?v:'';if(Number.isFinite(v))total+=v});s.total=total;return s}).filter(s=>s.name&&subjects.some((_,i)=>Number.isFinite(Number(s[`s${i}`]))));$('status').textContent=`已导入 ${students.length} 名学生`; $('studentSection').classList.remove('hidden');refresh()}catch(err){$('status').textContent='导入失败：'+err.message}};reader.readAsArrayBuffer(file)};
renderSubjects();
