const state={rows:[],subjects:[]};
const $=id=>document.getElementById(id);
function num(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function rankRows(rows,key){const sorted=[...rows].sort((a,b)=>(b[key]??0)-(a[key]??0));let last=null,r=0;return sorted.map((x,i)=>{if(x[key]!==last)r=i+1;last=x[key];return {...x,rank:r}})}
function parseRows(data){const rows=XLSX.utils.sheet_to_json(data,{defval:''});if(!rows.length)throw Error('Excel 没有数据');const headers=Object.keys(rows[0]);const nameKey=headers.find(h=>['姓名','名字','学生姓名'].includes(String(h).trim()))||headers[0];const subjectHeaders=state.subjects.length?state.subjects.map(s=>s.name).filter(n=>headers.some(h=>String(h).trim()===n)):headers.filter(h=>h!==nameKey);if(!subjectHeaders.length)throw Error('没有找到可用的科目列');const out=rows.map((r,i)=>{const name=String(r[nameKey]??'').trim();let total=0,has=false;const scores={};subjectHeaders.forEach(s=>{const h=headers.find(x=>String(x).trim()===s);const v=num(r[h]);scores[s]=v;if(v!==null){total+=v;has=true}});return{name:name||`第${i+1}行`,scores,total}}).filter(r=>r.name&&r.hasOwnProperty('total')&&Object.values(r.scores).some(v=>v!==null));return {rows:out,subjects:subjectHeaders.map(n=>{const old=state.subjects.find(s=>s.name===n);return old||{name:n,full:100}})}}
function render(){if(!state.rows.length)return;state.rows=rankRows(state.rows,'total');$('overview').classList.remove('hidden');const totals=state.rows.map(r=>r.total);$('stats').innerHTML=[['人数',state.rows.length],['平均总分',avg(totals).toFixed(1)],['最高分',Math.max(...totals)],['最低分',Math.min(...totals)]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
$('subjectOverview').innerHTML='<div class="grid">'+state.subjects.map(s=>{const vals=state.rows.map(r=>r.scores[s.name]).filter(v=>v!==null);const rates=vals.map(v=>v/s.full*100);return `<div class="card"><b>${esc(s.name)}</b><div>平均分：${avg(vals).toFixed(1)} / ${s.full}</div><div>平均得分率：${avg(rates).toFixed(1)}%</div><div>最高：${Math.max(...vals)}　最低：${Math.min(...vals)}</div></div>`}).join('')+'</div>';
const max=state.rows[0].total,min=state.rows[state.rows.length-1].total;const ranges=[['优秀',x=>x>=max*.85],['良好',x=>x>=max*.7&&x<max*.85],['中等',x=>x>=max*.55&&x<max*.7],['较低',x=>x<max*.55]];$('distribution').innerHTML='<div class="grid">'+ranges.map(([n,f])=>{const c=state.rows.filter(r=>f(r.total)).length;return `<div class="card"><b>${n}</b><div>${c} 人（${(c/state.rows.length*100).toFixed(1)}%）</div></div>`}).join('')+'</div><p class="small">分段按本班最高总分的比例计算，可用于快速观察成绩层次。</p>';
const attention=state.rows.filter(r=>r.total<=avg(totals)*.8||state.subjects.filter(s=>{const v=r.scores[s.name];return v!==null&&v/s.full<.6}).length>=2);$('attention').innerHTML=attention.length?'<div class="grid">'+attention.map(r=>`<div class="card danger"><b>${esc(r.name)}</b><div>总分 ${r.total}，排名 ${r.rank}</div><div>${weak(r)}</div></div>`).join('')+'</div>':'<p>目前没有自动识别出的重点关注学生。</p>';
$('rankTable').innerHTML='<tr><th>排名</th><th>姓名</th><th>总分</th>'+state.subjects.map(s=>`<th>${esc(s.name)}</th>`).join('')+'</tr>'+state.rows.map(r=>`<tr><td>${r.rank}</td><td>${esc(r.name)}</td><td class="highlight">${r.total}</td>`+state.subjects.map(s=>`<td>${r.scores[s.name]??'-'}</td>`).join('')+'</tr>').join('');
$('subjectSelect').innerHTML=state.subjects.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('');renderSubjectRank();renderSettings();}
function weak(r){const w=state.subjects.map(s=>({s,v:r.scores[s.name]})).filter(x=>x.v!==null).sort((a,b)=>a.v/a.s.full-b.v/b.s.full);return w.slice(0,2).map(x=>`${esc(x.s.name)} ${(x.v/x.s.full*100).toFixed(1)}%`).join('、')}
function renderSubjectRank(){const s=state.subjects.find(x=>x.name===$('subjectSelect').value);if(!s)return;const arr=state.rows.map(r=>({name:r.name,score:r.scores[s.name]})).filter(x=>x.score!==null);const ranked=rankRows(arr,'score');$('subjectRankTable').innerHTML='<tr><th>排名</th><th>姓名</th><th>成绩</th><th>得分率</th></tr>'+ranked.map(r=>`<tr><td>${r.rank}</td><td>${esc(r.name)}</td><td>${r.score}</td><td>${(r.score/s.full*100).toFixed(1)}%</td></tr>`).join('')}
function renderSettings(){$('settings').innerHTML=state.subjects.map((s,i)=>`<div class="setting"><input data-i="${i}" class="sname" value="${esc(s.name)}"><input data-i="${i}" class="sfull" type="number" min="1" value="${s.full}"></div>`).join('')}
function saveSettings(){const ns=[];document.querySelectorAll('.setting').forEach(el=>{const i=el.querySelector('.sname').dataset.i;const name=el.querySelector('.sname').value.trim();const full=num(el.querySelector('.sfull').value);if(name&&full>0)ns.push({name,full})});state.subjects=ns;render()}
$('file').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array'});const result=parseRows(wb.Sheets[wb.SheetNames[0]]);state.rows=result.rows;state.subjects=result.subjects;$('status').textContent=`已导入 ${state.rows.length} 名学生，共 ${state.subjects.length} 门科目`;render()}catch(err){$('status').textContent='导入失败：'+err.message}};reader.readAsArrayBuffer(f)});
$('searchBtn').addEventListener('click',()=>{const n=$('studentName').value.trim();const r=state.rows.find(x=>x.name===n);if(!r){$('studentDetail').innerHTML='<p class="muted">没有找到这个姓名，请检查输入。</p>';return}const ranks={};state.subjects.forEach(s=>{const arr=state.rows.map(x=>({name:x.name,score:x.scores[s.name]})).filter(x=>x.score!==null);ranks[s.name]=rankRows(arr,'score').find(x=>x.name===r.name)?.rank});$('studentDetail').innerHTML=`<div class="card ok"><h3>${esc(r.name)}</h3><p><b>总分：${r.total}</b>　班级排名：<b>${r.rank} / ${state.rows.length}</b></p><p>超过班级约 ${(100-(r.rank-1)/state.rows.length*100).toFixed(1)}% 的学生</p><div class="table-wrap"><table><tr><th>科目</th><th>成绩</th><th>满分</th><th>得分率</th><th>科目排名</th></tr>${state.subjects.map(s=>{const v=r.scores[s.name];return `<tr><td>${esc(s.name)}</td><td>${v??'-'}</td><td>${s.full}</td><td>${v===null?'-':(v/s.full*100).toFixed(1)+'%'}</td><td>${v===null?'-':ranks[s.name]}</td></tr>`}).join('')}</table></div><p><b>优势/薄弱：</b>${weak(r)||'暂无数据'}</p></div>`});
$('subjectSelect').addEventListener('change',renderSubjectRank);$('saveSettings').addEventListener('click',saveSettings);
